#!/usr/bin/env python3
"""Helpers for the code-project-guidance-map skill."""

from __future__ import annotations

import argparse
import base64
import binascii
import fnmatch
import hashlib
import hmac
import json
import os
import re
import secrets
import shlex
import shutil
import subprocess
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


START_MARKER = "<!-- code-project-guidance-map:start -->"
END_MARKER = "<!-- code-project-guidance-map:end -->"
GENERATOR = "code-project-guidance-map"
GENERATOR_VERSION = "0.2.1"
GUIDE_FORMAT = "action-map:v3"
SIGNATURE_ALGORITHM = "hmac-sha256:v2"
MODULE_START_MARKER = "<!-- code-project-guidance-map:module:start -->"
MODULE_END_MARKER = "<!-- code-project-guidance-map:module:end -->"
SIGNATURE_SECRET_ENV = "CODE_PROJECT_GUIDANCE_MAP_SECRET"
SIGNATURE_KEY_FILE_ENV = "CODE_PROJECT_GUIDANCE_MAP_KEY_FILE"
SIGNATURE_KEY_HOME_ENV = "CODE_PROJECT_GUIDANCE_MAP_KEY_HOME"
BUILD_HOME_ENV = "CODE_PROJECT_GUIDANCE_MAP_BUILD_HOME"
BUILD_CODEX_COMMAND_ENV = "CODE_PROJECT_GUIDANCE_MAP_CODEX_COMMAND"
BUILD_CODEX_VALIDATE_ENV = "CODE_PROJECT_GUIDANCE_MAP_VALIDATE_CODEX"
BUILD_LAUNCHER_ENV = "CODE_PROJECT_GUIDANCE_MAP_LAUNCHER"
BUILD_DESKTOP_LAUNCH_GRACE_SECONDS_ENV = "CODE_PROJECT_GUIDANCE_MAP_DESKTOP_LAUNCH_GRACE_SECONDS"
BUILD_STALE_SECONDS_ENV = "CODE_PROJECT_GUIDANCE_MAP_BUILD_STALE_SECONDS"
BUILD_STATE_LOCK_TIMEOUT_ENV = "CODE_PROJECT_GUIDANCE_MAP_BUILD_STATE_LOCK_TIMEOUT"
DEFAULT_BUILD_STALE_SECONDS = 6 * 60 * 60
DEFAULT_DESKTOP_LAUNCH_GRACE_SECONDS = 10 * 60
DEFAULT_BUILD_STATE_LOCK_TIMEOUT_SECONDS = 10.0
BUILD_LAUNCH_GRACE_SECONDS = 60.0
GENERATED_AT_RE = re.compile(r"^Generated at:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GENERATOR_RE = re.compile(r"^Generator:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GENERATOR_VERSION_RE = re.compile(r"^Generator version:\s*(?P<value>.+?)\s*$", re.MULTILINE)
LEGACY_GENERATED_BY_RE = re.compile(r"^Generated by:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GUIDE_FORMAT_RE = re.compile(r"^Guide format:\s*(?P<value>.+?)\s*$", re.MULTILINE)
GIT_BASELINE_RE = re.compile(r"^Git baseline:\s*(?P<value>.+?)\s*$", re.MULTILINE)
LOCAL_CHANGE_BASELINE_RE = re.compile(r"^Local change baseline:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_KEY_ID_RE = re.compile(r"^Signature key id:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_ALGORITHM_RE = re.compile(r"^Signature algorithm:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SIGNATURE_RE = re.compile(r"^Signature:\s*(?P<value>.+?)\s*$", re.MULTILINE)
SECTION_HEADING_RE = re.compile(r"^### (?!#)(?P<title>.+?)\s*$", re.MULTILINE)
MODULE_HEADING_RE = re.compile(r"^#### (?!#)(?P<title>.+?)\s*$", re.MULTILINE)
REQUIRED_GUIDE_SECTIONS = (
    "Agent Editing Rules",
    "Task Routing",
    "Module Dependency Rules",
    "Module Index",
)
REQUIRED_INDEX_MODULE_FIELDS = (
    "Module Path",
    "Module Guide",
    "Module Signature",
    "Owns",
    "Change here when",
    "Do not put here",
)
REQUIRED_MODULE_GUIDE_FIELDS = (
    "Module Path",
    "Owns",
    "Change here when",
    "Do not put here",
    "Key entry points",
)

BOUNDARY_SENSITIVE_PATTERNS = (
    "pom.xml",
    "**/pom.xml",
    "build.gradle",
    "**/build.gradle",
    "build.gradle.kts",
    "**/build.gradle.kts",
    "settings.gradle",
    "**/settings.gradle",
    "settings.gradle.kts",
    "**/settings.gradle.kts",
    "package.json",
    "**/package.json",
    "pnpm-workspace.yaml",
    "tsconfig.json",
    "**/tsconfig.json",
    "vite.config.*",
    "**/vite.config.*",
    "webpack.config.*",
    "**/webpack.config.*",
    "pyproject.toml",
    "requirements*.txt",
    "go.mod",
    "Cargo.toml",
    "*.sln",
    "*.csproj",
    "**/*.csproj",
)
TASK_ROUTING_PATTERNS = (
    "**/controller/**",
    "**/controllers/**",
    "**/routes/**",
    "**/api/**",
    "**/service/**",
    "**/services/**",
    "**/dao/**",
    "**/repository/**",
    "**/repositories/**",
    "**/resources/mappings/**",
    "**/mapper/**",
    "**/mappers/**",
    "**/job/**",
    "**/jobs/**",
    "**/task/**",
    "**/tasks/**",
    "**/schedule/**",
    "**/scheduler/**",
    "**/websocket/**",
    "**/mq/**",
    "**/queue/**",
    "**/*Controller.*",
    "**/*Service.*",
    "**/*Dao.*",
    "**/*DAO.*",
    "**/*Mapper.*",
    "**/*Repository.*",
    "**/*Job.*",
    "**/*Task.*",
    "**/*Scheduler.*",
)
CODE_PATTERNS = (
    "*.java",
    "*.kt",
    "*.ts",
    "*.tsx",
    "*.js",
    "*.jsx",
    "*.py",
    "*.go",
    "*.rs",
    "*.cs",
    "*.php",
    "*.rb",
    "*.sql",
    "*.xml",
    "*.yaml",
    "*.yml",
)
DOCS_PATTERNS = (
    "*.md",
    "README*",
    "LICENSE",
    "docs/**",
    ".github/**",
)
GENERATED_GUIDANCE_PATTERNS = (
    "AGENTS.md",
    ".agents/guidance-map/**",
)
DETACHED_BUILDER_PROCESSES: list[subprocess.Popen[str]] = []


class GuidanceMapError(RuntimeError):
    """Raised for user-fixable guidance map errors."""


def run_git(repo: Path, args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def repo_root(start: Path) -> tuple[Path, bool]:
    result = run_git(start, ["rev-parse", "--show-toplevel"])
    if result.returncode == 0:
        return Path(result.stdout.strip()).resolve(), True
    return start.resolve(), False


def current_head(repo: Path, git_available: bool) -> str:
    if not git_available:
        return "none"
    result = run_git(repo, ["rev-parse", "--short", "HEAD"])
    if result.returncode != 0:
        return "none"
    value = result.stdout.strip()
    return value or "none"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")


def find_block(text: str) -> tuple[int, int, str] | None:
    start_count = text.count(START_MARKER)
    end_count = text.count(END_MARKER)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1:
        raise GuidanceMapError("Malformed guidance block markers: expected exactly one start and one end marker.")
    start = text.index(START_MARKER)
    end_marker_start = text.index(END_MARKER)
    if end_marker_start < start:
        raise GuidanceMapError("Malformed guidance block markers: end marker appears before start marker.")
    end = end_marker_start + len(END_MARKER)
    return start, end, text[start:end]


def metadata_value(pattern: re.Pattern[str], block: str | None) -> str | None:
    if not block:
        return None
    match = pattern.search(block)
    if not match:
        return None
    return match.group("value").strip()


def parse_iso_datetime(value: str | None) -> datetime | None:
    if not value:
        return None
    normalized = value.strip()
    if normalized.endswith("Z"):
        normalized = f"{normalized[:-1]}+00:00"
    try:
        parsed = datetime.fromisoformat(normalized)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def parse_semver(value: str | None) -> tuple[int, int, int] | None:
    if not value:
        return None
    match = re.fullmatch(r"(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)", value.strip())
    if not match:
        return None
    return int(match.group(1)), int(match.group(2)), int(match.group(3))


def generator_version_status(version: str | None, current: str = GENERATOR_VERSION) -> str:
    parsed = parse_semver(version)
    current_parsed = parse_semver(current)
    if version is None:
        return "missing"
    if parsed is None or current_parsed is None:
        return "invalid"
    if parsed == current_parsed:
        return "current"
    if parsed[:2] == current_parsed[:2]:
        return "patch-compatible"
    return "incompatible"


def unique_ordered(values: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        value = value.strip().replace("\\", "/")
        if not value or value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def matches_any(path: str, patterns: Iterable[str]) -> bool:
    normalized = path.strip().replace("\\", "/")
    return any(fnmatch.fnmatchcase(normalized, pattern) for pattern in patterns)


def is_generated_guidance_path(path: str) -> bool:
    return matches_any(path, GENERATED_GUIDANCE_PATTERNS)


def classify_changed_files(files: Iterable[str]) -> dict[str, list[str]]:
    impact = {
        "boundary_rules": [],
        "task_routing": [],
        "module_internal": [],
        "docs_only": [],
        "other": [],
    }
    for file in unique_ordered(files):
        if matches_any(file, BOUNDARY_SENSITIVE_PATTERNS):
            impact["boundary_rules"].append(file)
        elif matches_any(file, TASK_ROUTING_PATTERNS):
            impact["task_routing"].append(file)
        elif matches_any(file, DOCS_PATTERNS):
            impact["docs_only"].append(file)
        elif matches_any(file, CODE_PATTERNS):
            impact["module_internal"].append(file)
        else:
            impact["other"].append(file)
    return impact


def git_files(repo: Path, args: list[str]) -> list[str]:
    result = run_git(repo, args)
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.strip()]


def file_content_state(repo: Path, relpath: str) -> str:
    path = (repo / relpath).resolve()
    try:
        path.relative_to(repo.resolve())
    except ValueError:
        return "outside"
    try:
        if not path.exists():
            return "missing"
        if not path.is_file():
            return "non-file"
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError:
        return "unreadable"
    return f"sha256:{digest}"


def encode_local_change_baseline(entries: dict[str, str]) -> str:
    normalized = [[path, entries[path]] for path in sorted(entries)]
    payload = json.dumps(normalized, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    encoded = base64.urlsafe_b64encode(payload).decode("ascii").rstrip("=")
    digest = hashlib.sha256(payload).hexdigest()
    return f"sha256:{digest}:{encoded}"


def decode_local_change_baseline(value: str | None) -> tuple[dict[str, str], bool]:
    if value is None:
        return {}, True
    pieces = value.strip().split(":", 2)
    if len(pieces) != 3 or pieces[0] != "sha256" or not re.fullmatch(r"[0-9a-f]{64}", pieces[1]):
        return {}, False
    encoded = pieces[2]
    try:
        padding = "=" * (-len(encoded) % 4)
        payload = base64.urlsafe_b64decode((encoded + padding).encode("ascii"))
        if hashlib.sha256(payload).hexdigest() != pieces[1]:
            return {}, False
        decoded = json.loads(payload.decode("utf-8"))
    except (OSError, ValueError, binascii.Error, json.JSONDecodeError):
        return {}, False
    if not isinstance(decoded, list):
        return {}, False
    entries: dict[str, str] = {}
    for item in decoded:
        if not (
            isinstance(item, list)
            and len(item) == 2
            and isinstance(item[0], str)
            and isinstance(item[1], str)
        ):
            return {}, False
        path = item[0].strip().replace("\\", "/")
        state = item[1].strip()
        if not path or path.startswith("../") or "/../" in path or path in {".", ".."}:
            return {}, False
        entries[path] = state
    return entries, True


def local_change_baseline(repo: Path, git_available: bool) -> str:
    if not git_available:
        return encode_local_change_baseline({})
    local_files = unique_ordered(
        [
            *git_files(repo, ["diff", "--name-only", "--cached"]),
            *git_files(repo, ["diff", "--name-only"]),
            *git_files(repo, ["ls-files", "--others", "--exclude-standard"]),
        ]
    )
    entries = {
        file: file_content_state(repo, file)
        for file in local_files
        if not is_generated_guidance_path(file)
    }
    return encode_local_change_baseline(entries)


def baseline_ignored_files(repo: Path, files: Iterable[str], baseline: dict[str, str]) -> list[str]:
    ignored: list[str] = []
    for file in unique_ordered(files):
        expected = baseline.get(file)
        if expected is not None and file_content_state(repo, file) == expected:
            ignored.append(file)
    return ignored


def filter_baseline_ignored(files: Iterable[str], ignored: set[str]) -> list[str]:
    return [file for file in unique_ordered(files) if file not in ignored]


def changed_files(
    repo: Path,
    git_available: bool,
    since: datetime | None,
    baseline: dict[str, str] | None = None,
) -> dict[str, list[str]]:
    if not git_available:
        return {
            "committed": [],
            "staged": [],
            "unstaged": [],
            "untracked": [],
            "baseline_ignored": [],
            "all": [],
        }

    committed: list[str] = []
    if since is not None:
        since_arg = since.strftime("%Y-%m-%d %H:%M:%S %z")
        committed = git_files(repo, ["log", f"--since={since_arg}", "--name-only", "--pretty=format:"])

    staged = git_files(repo, ["diff", "--name-only", "--cached"])
    unstaged = git_files(repo, ["diff", "--name-only"])
    untracked = git_files(repo, ["ls-files", "--others", "--exclude-standard"])
    all_files = unique_ordered([*committed, *staged, *unstaged, *untracked])
    ignored_list = baseline_ignored_files(repo, all_files, baseline or {})
    ignored = set(ignored_list)

    return {
        "committed": filter_baseline_ignored(committed, ignored),
        "staged": filter_baseline_ignored(staged, ignored),
        "unstaged": filter_baseline_ignored(unstaged, ignored),
        "untracked": filter_baseline_ignored(untracked, ignored),
        "baseline_ignored": ignored_list,
        "all": filter_baseline_ignored(all_files, ignored),
    }


def repo_identity(repo: Path, git_available: bool) -> str:
    if git_available:
        remote = run_git(repo, ["config", "--get", "remote.origin.url"])
        if remote.returncode == 0 and remote.stdout.strip():
            return f"git:{remote.stdout.strip()}"
    return f"path:{repo.resolve()}"


def project_id(repo: Path, git_available: bool) -> str:
    digest = hashlib.sha256(repo_identity(repo, git_available).encode("utf-8")).hexdigest()
    return f"repo:{digest[:16]}"


def default_signature_key_id(repo: Path, git_available: bool) -> str:
    return project_id(repo, git_available)


def codex_home() -> Path:
    configured = os.environ.get("CODEX_HOME")
    if configured:
        return Path(configured).expanduser()
    return Path.home() / ".codex"


def utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def safe_token(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value.strip()) or "unknown"


def build_home() -> Path:
    configured = os.environ.get(BUILD_HOME_ENV)
    if configured:
        return Path(configured).expanduser()
    return codex_home() / "code-project-guidance-map" / "builds"


def build_state_dir(repo: Path, git_available: bool) -> Path:
    return build_home() / safe_token(project_id(repo, git_available))


def build_state_path(state_dir: Path) -> Path:
    return state_dir / "state-v1.json"


def build_active_lock_path(state_dir: Path) -> Path:
    return state_dir / "active-build.lock"


def build_state_mutex_path(state_dir: Path) -> Path:
    return state_dir / "state-write.lock"


def read_json_file(path: Path) -> dict[str, Any]:
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def write_json_file(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f"{path.name}.{os.getpid()}.{uuid.uuid4().hex}.tmp")
    tmp.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8", newline="\n")
    tmp.replace(path)


def read_build_state(state_dir: Path, repo: Path, git_available: bool) -> dict[str, Any]:
    state = read_json_file(build_state_path(state_dir))
    state.setdefault("version", 1)
    state.setdefault("project_id", project_id(repo, git_available))
    state.setdefault("repo_root", str(repo))
    state.setdefault("pending_contexts", [])
    state.setdefault("history", [])
    if not isinstance(state["pending_contexts"], list):
        state["pending_contexts"] = []
    if not isinstance(state["history"], list):
        state["history"] = []
    return state


def write_build_state(state_dir: Path, state: dict[str, Any]) -> None:
    write_json_file(build_state_path(state_dir), state)


def env_float(name: str, default: float) -> float:
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        value = float(raw)
    except ValueError:
        return default
    return value if value > 0 else default


def parse_timestamp_seconds(value: str | None) -> float | None:
    parsed = parse_iso_datetime(value)
    if parsed is None:
        return None
    return parsed.timestamp()


def process_is_running(pid: int | None) -> bool:
    if pid is None or pid <= 0:
        return False
    if os.name == "nt":
        try:
            result = subprocess.run(
                ["tasklist", "/FI", f"PID eq {pid}", "/FO", "CSV", "/NH"],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                check=False,
            )
        except OSError:
            return False
        return result.returncode == 0 and str(pid) in result.stdout
    try:
        os.kill(pid, 0)
    except OSError:
        return False
    return True


def active_build_is_live(active: dict[str, Any] | None) -> bool:
    if not isinstance(active, dict):
        return False
    status_value = str(active.get("status") or "")
    launcher = str(active.get("launcher") or "")
    started_at = parse_timestamp_seconds(str(active.get("started_at") or ""))
    age = (time.time() - started_at) if started_at is not None else None
    if status_value == "launching" and age is not None and age < BUILD_LAUNCH_GRACE_SECONDS:
        return True
    if status_value == "desktop_launch_required" and age is not None:
        desktop_launch_grace = env_float(BUILD_DESKTOP_LAUNCH_GRACE_SECONDS_ENV, float(DEFAULT_DESKTOP_LAUNCH_GRACE_SECONDS))
        return age < desktop_launch_grace
    pid_value = active.get("pid")
    try:
        pid = int(pid_value) if pid_value is not None else None
    except (TypeError, ValueError):
        pid = None
    if process_is_running(pid):
        return True
    stale_after = env_float(BUILD_STALE_SECONDS_ENV, float(DEFAULT_BUILD_STALE_SECONDS))
    if launcher == "desktop" and status_value == "running":
        return bool(age is not None and age < stale_after and active.get("thread_id"))
    return bool(age is not None and age < stale_after and status_value == "starting")


def read_active_lock(state_dir: Path) -> dict[str, Any] | None:
    loaded = read_json_file(build_active_lock_path(state_dir))
    return loaded if loaded else None


def write_active_lock(state_dir: Path, active: dict[str, Any]) -> None:
    write_json_file(build_active_lock_path(state_dir), active)


def remove_active_lock(state_dir: Path, build_id: str | None = None) -> None:
    path = build_active_lock_path(state_dir)
    if build_id:
        existing = read_active_lock(state_dir)
        if existing and existing.get("build_id") != build_id:
            return
    try:
        path.unlink()
    except OSError:
        pass


class BuildStateMutex:
    def __init__(self, state_dir: Path) -> None:
        self.state_dir = state_dir
        self.path = build_state_mutex_path(state_dir)
        self.fd: int | None = None

    def __enter__(self) -> "BuildStateMutex":
        self.state_dir.mkdir(parents=True, exist_ok=True)
        deadline = time.time() + env_float(BUILD_STATE_LOCK_TIMEOUT_ENV, DEFAULT_BUILD_STATE_LOCK_TIMEOUT_SECONDS)
        while True:
            try:
                self.fd = os.open(str(self.path), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
                os.write(self.fd, json.dumps({"pid": os.getpid(), "created_at": utc_now()}).encode("utf-8"))
                return self
            except FileExistsError:
                try:
                    age = time.time() - self.path.stat().st_mtime
                except OSError:
                    age = 0
                if age > DEFAULT_BUILD_STATE_LOCK_TIMEOUT_SECONDS:
                    try:
                        self.path.unlink()
                    except OSError:
                        pass
                    continue
                if time.time() >= deadline:
                    raise GuidanceMapError(f"Timed out waiting for build state lock: {self.path}")
                time.sleep(0.1)

    def __exit__(self, exc_type: object, exc: object, tb: object) -> None:
        if self.fd is not None:
            try:
                os.close(self.fd)
            except OSError:
                pass
        try:
            self.path.unlink()
        except OSError:
            pass


def append_history(state: dict[str, Any], active: dict[str, Any], status_value: str, message: str | None = None) -> None:
    history = state.setdefault("history", [])
    if not isinstance(history, list):
        history = []
        state["history"] = history
    entry = dict(active)
    entry["finished_at"] = utc_now()
    entry["finish_status"] = status_value
    if message:
        entry["message"] = message
    history.append(entry)
    del history[:-20]


def clear_active_build(state_dir: Path, state: dict[str, Any], status_value: str, message: str | None = None) -> None:
    active = state.pop("active", None)
    if isinstance(active, dict):
        append_history(state, active, status_value, message)
        remove_active_lock(state_dir, str(active.get("build_id") or ""))


def ensure_active_from_lock(state_dir: Path, state: dict[str, Any]) -> dict[str, Any] | None:
    active = state.get("active")
    if isinstance(active, dict):
        return active
    lock = read_active_lock(state_dir)
    if isinstance(lock, dict):
        state["active"] = lock
        return lock
    return None


def normalize_context_text(context: str | None, context_file: Path | None) -> str:
    pieces: list[str] = []
    if context:
        pieces.append(context.strip())
    if context_file:
        try:
            pieces.append(context_file.read_text(encoding="utf-8").strip())
        except OSError as exc:
            raise GuidanceMapError(f"Unable to read build context file {context_file}: {exc}") from exc
    text = "\n\n".join(piece for piece in pieces if piece)
    if len(text) > 60000:
        return text[:60000] + "\n\n[context truncated by guidance_map.py build]"
    return text


def build_request_context(
    repo: Path,
    verification: dict[str, object],
    reason: str | None,
    context: str | None,
    context_file: Path | None,
) -> dict[str, Any]:
    return {
        "request_id": uuid.uuid4().hex,
        "requested_at": utc_now(),
        "repo_root": str(repo),
        "reason": reason or str(verification.get("recommended_action") or "refresh"),
        "context": normalize_context_text(context, context_file),
        "recommended_action": verification.get("recommended_action"),
        "severity": verification.get("severity"),
        "changed_files": verification.get("changed_files"),
        "affected_module_guides": verification.get("affected_module_guides"),
        "reasons": verification.get("reasons"),
    }


def builder_prompt(
    repo: Path,
    build_id: str,
    script_path: Path,
    verification: dict[str, object],
    request_context: dict[str, Any],
    state_dir: Path,
) -> str:
    return f"""You are the script-coordinated Code Project Guidance Map builder agent.

Repository: {repo}
Build id: {build_id}
Build state directory: {state_dir}

This is the only mode allowed to construct or refresh the guidance map. Do not run `guidance_map.py build` and do not start another builder. Other Codex threads synchronize context through the build state while you own this lease.

Your task:
1. Read the local `code-project-guidance-map` skill instructions. Because this prompt was launched by `guidance_map.py build`, operate in Builder Agent Mode: perform the direct map construction workflow in this agent instead of delegating back to `build`.
2. Run `python {script_path} status --repo {repo}` and `python {script_path} verify --repo {repo}`.
3. If the guidance is current and no refresh was explicitly requested, release the lease with `python {script_path} build-finish --repo {repo} --build-id {build_id} --status complete`.
4. For generate, full refresh, or incremental refresh work, use bounded module subagents exactly as the skill requires. The main builder owns only shallow scanning, macro module boundaries, index integration, and final helper commands.
5. Write module guides, create the temporary index draft, then run `python {script_path} update --repo {repo} --guidance-file <temp-index.md>`.
6. Validate with `python {script_path} status --repo {repo}`.
7. Before finalizing, run `python {script_path} build-drain --repo {repo} --build-id {build_id}`. If it returns pending contexts, fold them into your working context, re-run `verify`, and perform another build pass. Repeat until `pending_contexts` is empty.
8. Release the lease only after the final pass with `python {script_path} build-finish --repo {repo} --build-id {build_id} --status complete`. If you cannot complete, run the same command with `--status failed --message <reason>`.

Initial verification JSON:
```json
{json.dumps(verification, ensure_ascii=False, indent=2)}
```

Initial request context:
```json
{json.dumps(request_context, ensure_ascii=False, indent=2)}
```
"""


def desktop_codex_install_hint() -> str | None:
    if os.name != "nt":
        return None
    try:
        program_files = Path(os.environ.get("ProgramFiles") or r"C:\Program Files")
        matches = sorted(program_files.glob(r"WindowsApps/OpenAI.Codex_*/app/resources/codex.exe"))
    except OSError:
        matches = []
    if not matches:
        return None
    return str(matches[-1])


def validate_default_codex(command: list[str]) -> None:
    if os.environ.get(BUILD_CODEX_VALIDATE_ENV, "1").strip().casefold() in {"0", "false", "no", "off"}:
        return
    try:
        result = subprocess.run(
            [*command, "--version"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        hint = desktop_codex_install_hint()
        desktop_note = (
            f" A Codex Desktop package appears to be installed at {hint}, but that WindowsApps path may not be directly executable by scripts."
            if hint
            else ""
        )
        raise GuidanceMapError(
            "Unable to run `codex --version` for the CLI launcher; use a runnable Codex CLI command on PATH, "
            "CODE_PROJECT_GUIDANCE_MAP_CODEX_COMMAND/--codex-command, or `guidance_map.py build --launcher auto` from Codex Desktop."
            f"{desktop_note}"
        ) from exc
    if result.returncode != 0:
        stderr = result.stderr.strip() or result.stdout.strip()
        raise GuidanceMapError(f"`codex --version` failed with code {result.returncode}: {stderr}")


def resolve_codex_command(codex_command: str | None) -> list[str]:
    configured = codex_command or os.environ.get(BUILD_CODEX_COMMAND_ENV)
    if configured:
        command = shlex.split(configured, posix=os.name != "nt")
        if not command:
            raise GuidanceMapError("Codex command is empty.")
        return command

    executable = shutil.which("codex")
    if not executable:
        hint = desktop_codex_install_hint()
        desktop_note = (
            f" A Codex Desktop package appears to be installed at {hint}, but no runnable `codex` command is exposed on PATH."
            if hint
            else ""
        )
        raise GuidanceMapError(
            "Unable to find a runnable `codex` command for the CLI launcher. The build helper can use Codex CLI, including "
            "a Desktop-provided command alias, or `guidance_map.py build --launcher auto` can hand off from Codex Desktop."
            f"{desktop_note}"
        )
    command = [executable]
    validate_default_codex(command)
    return command


def normalize_build_launcher(launcher: str | None) -> str:
    value = (launcher or os.environ.get(BUILD_LAUNCHER_ENV) or "auto").strip().casefold()
    if value not in {"auto", "cli", "desktop"}:
        raise GuidanceMapError("Build launcher must be one of: auto, cli, desktop.")
    return value


def desktop_launcher_available() -> bool:
    return os.environ.get("CODEX_INTERNAL_ORIGINATOR_OVERRIDE", "").strip().casefold() == "codex desktop"


def resolve_build_launcher(launcher: str | None, codex_command: str | None) -> tuple[str, list[str] | None, str | None]:
    launcher_value = normalize_build_launcher(launcher)
    explicit_command = bool(codex_command or os.environ.get(BUILD_CODEX_COMMAND_ENV))
    if launcher_value == "desktop":
        if not desktop_launcher_available():
            return "desktop", None, "Desktop launcher was requested; create_thread must be available in the current Codex app thread."
        return "desktop", None, None

    try:
        return "cli", resolve_codex_command(codex_command), None
    except GuidanceMapError as exc:
        if launcher_value == "auto" and not explicit_command and desktop_launcher_available():
            return "desktop", None, str(exc)
        raise


def launch_builder_agent(
    repo: Path,
    build_id: str,
    prompt: str,
    state_dir: Path,
    codex_command: str | None,
    model: str | None,
    extra_args: list[str],
    resolved_command: list[str] | None = None,
) -> dict[str, Any]:
    command = resolved_command or resolve_codex_command(codex_command)

    log_dir = state_dir / "logs"
    log_dir.mkdir(parents=True, exist_ok=True)
    prompt_file = log_dir / f"{build_id}.prompt.md"
    log_file = log_dir / f"{build_id}.jsonl"
    last_message_file = log_dir / f"{build_id}.last-message.md"
    write_text(prompt_file, prompt)

    cmd = [
        *command,
        "exec",
        "--cd",
        str(repo),
        "--json",
        "-o",
        str(last_message_file),
    ]
    if model:
        cmd.extend(["--model", model])
    cmd.extend(extra_args)
    cmd.append("-")

    env = os.environ.copy()
    env["CODE_PROJECT_GUIDANCE_MAP_BUILD_ID"] = build_id
    env["CODE_PROJECT_GUIDANCE_MAP_BUILD_STATE_DIR"] = str(state_dir)
    creationflags = 0
    start_new_session = os.name != "nt"
    if os.name == "nt":
        creationflags = getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0) | getattr(subprocess, "DETACHED_PROCESS", 0)
    log_handle = log_file.open("a", encoding="utf-8")
    try:
        process = subprocess.Popen(
            cmd,
            cwd=str(repo),
            env=env,
            stdin=subprocess.PIPE,
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            text=True,
            start_new_session=start_new_session,
            creationflags=creationflags,
        )
        assert process.stdin is not None
        process.stdin.write(prompt)
        process.stdin.close()
        time.sleep(0.2)
        if process.poll() is not None:
            raise GuidanceMapError(f"Builder agent exited during startup with code {process.returncode}. See {log_file}.")
        DETACHED_BUILDER_PROCESSES.append(process)
        return {
            "pid": process.pid,
            "command": cmd,
            "prompt_file": str(prompt_file),
            "log_file": str(log_file),
            "last_message_file": str(last_message_file),
        }
    except OSError as exc:
        raise GuidanceMapError(f"Unable to launch builder agent: {exc}") from exc
    finally:
        log_handle.close()
def start_guidance_build(
    repo_arg: Path,
    reason: str | None = None,
    context: str | None = None,
    context_file: Path | None = None,
    codex_command: str | None = None,
    model: str | None = None,
    extra_args: list[str] | None = None,
    launcher: str | None = None,
) -> dict[str, Any]:
    root, git_available = repo_root(repo_arg)
    verification = verify(root)
    state_dir = build_state_dir(root, git_available)
    state_dir.mkdir(parents=True, exist_ok=True)
    request_context = build_request_context(root, verification, reason, context, context_file)
    script_path = Path(__file__).resolve()

    with BuildStateMutex(state_dir):
        state = read_build_state(state_dir, root, git_available)
        active = ensure_active_from_lock(state_dir, state)
        if active_build_is_live(active):
            pending = state.setdefault("pending_contexts", [])
            pending.append(request_context)
            write_build_state(state_dir, state)
            return {
                "status": "queued",
                "repo_root": str(root),
                "project_id": project_id(root, git_available),
                "active_build_id": active.get("build_id") if isinstance(active, dict) else None,
                "pending_context_count": len(pending),
                "state_file": str(build_state_path(state_dir)),
                "message": "A guidance-map builder is already running; context was synchronized for the active builder to consume before it finishes.",
            }

        if active:
            clear_active_build(state_dir, state, "stale", "Active builder was not running; replacing stale lease.")

        launcher_value, resolved_command, launcher_note = resolve_build_launcher(launcher, codex_command)
        build_id = uuid.uuid4().hex
        started_at = utc_now()
        prompt = builder_prompt(root, build_id, script_path, verification, request_context, state_dir)
        active = {
            "build_id": build_id,
            "repo_root": str(root),
            "project_id": project_id(root, git_available),
            "status": "launching" if launcher_value == "cli" else "desktop_launch_required",
            "launcher": launcher_value,
            "started_at": started_at,
            "pid": None,
        }
        state["active"] = active
        state.setdefault("pending_contexts", [])
        write_active_lock(state_dir, active)
        write_build_state(state_dir, state)

        if launcher_value == "desktop":
            log_dir = state_dir / "logs"
            log_dir.mkdir(parents=True, exist_ok=True)
            prompt_file = log_dir / f"{build_id}.prompt.md"
            write_text(prompt_file, prompt)
            active["prompt_file"] = str(prompt_file)
            if launcher_note:
                active["launcher_note"] = launcher_note
            write_active_lock(state_dir, active)
            write_build_state(state_dir, state)
            return {
                "status": "desktop_launch_required",
                "repo_root": str(root),
                "project_id": project_id(root, git_available),
                "build_id": build_id,
                "launcher": "desktop",
                "state_file": str(build_state_path(state_dir)),
                "prompt_file": str(prompt_file),
                "prompt": prompt,
                "attach_command": f"python {script_path} build-attach --repo {root} --build-id {build_id} --thread-id <created-thread-id>",
                "finish_failed_command": f"python {script_path} build-finish --repo {root} --build-id {build_id} --status failed --force --message <reason>",
                "message": (
                    "No runnable CLI builder was launched. In Codex Desktop, create a new local project thread with the returned prompt, "
                    "then run build-attach with the created thread id. The lease prevents another map builder from starting meanwhile."
                ),
            }

        try:
            launch = launch_builder_agent(
                root,
                build_id,
                prompt,
                state_dir,
                codex_command,
                model,
                extra_args or [],
                resolved_command=resolved_command,
            )
        except GuidanceMapError:
            clear_active_build(state_dir, state, "launch_failed", "Builder agent failed to start.")
            write_build_state(state_dir, state)
            raise

        active.update(
            {
                "status": "running",
                "launcher": "cli",
                "pid": launch["pid"],
                "command": launch["command"],
                "prompt_file": launch["prompt_file"],
                "log_file": launch["log_file"],
                "last_message_file": launch["last_message_file"],
            }
        )
        write_active_lock(state_dir, active)
        write_build_state(state_dir, state)
        return {
            "status": "started",
            "repo_root": str(root),
            "project_id": project_id(root, git_available),
            "build_id": build_id,
            "launcher": "cli",
            "pid": launch["pid"],
            "state_file": str(build_state_path(state_dir)),
            "prompt_file": launch["prompt_file"],
            "log_file": launch["log_file"],
            "last_message_file": launch["last_message_file"],
            "message": "Builder agent started; guidance_map.py build is exiting now.",
        }


def attach_desktop_builder_thread(repo_arg: Path, build_id: str, thread_id: str) -> dict[str, Any]:
    root, git_available = repo_root(repo_arg)
    state_dir = build_state_dir(root, git_available)
    with BuildStateMutex(state_dir):
        state = read_build_state(state_dir, root, git_available)
        active = ensure_active_from_lock(state_dir, state)
        if not isinstance(active, dict) or active.get("build_id") != build_id:
            raise GuidanceMapError("Build id does not match the active guidance-map builder.")
        if str(active.get("launcher") or "") != "desktop":
            raise GuidanceMapError("Active builder was not prepared for Desktop thread attachment.")
        active.update(
            {
                "status": "running",
                "thread_id": thread_id,
                "attached_at": utc_now(),
            }
        )
        state["active"] = active
        write_active_lock(state_dir, active)
        write_build_state(state_dir, state)
        return {
            "status": "attached",
            "repo_root": str(root),
            "build_id": build_id,
            "thread_id": thread_id,
            "state_file": str(build_state_path(state_dir)),
            "message": "Desktop builder thread attached; guidance_map.py build coordination can stop in the caller thread.",
        }


def drain_build_context(repo_arg: Path, build_id: str) -> dict[str, Any]:
    root, git_available = repo_root(repo_arg)
    state_dir = build_state_dir(root, git_available)
    with BuildStateMutex(state_dir):
        state = read_build_state(state_dir, root, git_available)
        active = ensure_active_from_lock(state_dir, state)
        if not isinstance(active, dict) or active.get("build_id") != build_id:
            raise GuidanceMapError("Build id does not match the active guidance-map builder.")
        pending = state.get("pending_contexts") if isinstance(state.get("pending_contexts"), list) else []
        state["pending_contexts"] = []
        write_build_state(state_dir, state)
        return {
            "status": "drained",
            "repo_root": str(root),
            "build_id": build_id,
            "pending_contexts": pending,
            "pending_context_count": len(pending),
            "state_file": str(build_state_path(state_dir)),
        }


def finish_guidance_build(
    repo_arg: Path,
    build_id: str,
    status_value: str,
    message: str | None = None,
    force: bool = False,
) -> dict[str, Any]:
    root, git_available = repo_root(repo_arg)
    state_dir = build_state_dir(root, git_available)
    with BuildStateMutex(state_dir):
        state = read_build_state(state_dir, root, git_available)
        active = ensure_active_from_lock(state_dir, state)
        if not isinstance(active, dict) or active.get("build_id") != build_id:
            raise GuidanceMapError("Build id does not match the active guidance-map builder.")
        pending = state.get("pending_contexts") if isinstance(state.get("pending_contexts"), list) else []
        if pending and not force:
            raise GuidanceMapError("Pending build context exists; run build-drain and perform another build pass before finishing.")
        clear_active_build(state_dir, state, status_value, message)
        write_build_state(state_dir, state)
        return {
            "status": "finished",
            "finish_status": status_value,
            "repo_root": str(root),
            "build_id": build_id,
            "pending_context_count": len(pending),
            "state_file": str(build_state_path(state_dir)),
        }


def signature_key_path(key_id: str) -> Path:
    key_home = os.environ.get(SIGNATURE_KEY_HOME_ENV)
    root = Path(key_home).expanduser() if key_home else codex_home() / "code-project-guidance-map" / "keys"
    safe_key_id = re.sub(r"[^A-Za-z0-9_.-]+", "_", key_id)
    return root / f"{safe_key_id}.key"


def normalize_secret(raw: str) -> bytes:
    value = raw.strip()
    if re.fullmatch(r"[0-9a-fA-F]{64}", value):
        return bytes.fromhex(value)
    return value.encode("utf-8")


def load_signature_secret(key_id: str | None, create: bool) -> tuple[bytes | None, bool, str | None]:
    env_secret = os.environ.get(SIGNATURE_SECRET_ENV)
    if env_secret:
        return normalize_secret(env_secret), True, SIGNATURE_SECRET_ENV

    key_file_env = os.environ.get(SIGNATURE_KEY_FILE_ENV)
    if key_file_env:
        path = Path(key_file_env).expanduser()
    elif key_id:
        path = signature_key_path(key_id)
    else:
        return None, False, None

    if path.exists():
        return normalize_secret(read_text(path)), True, str(path)
    if not create:
        return None, False, str(path)

    path.parent.mkdir(parents=True, exist_ok=True)
    secret = secrets.token_hex(32)
    write_text(path, f"{secret}\n")
    try:
        path.chmod(0o600)
    except OSError:
        pass
    return bytes.fromhex(secret), True, str(path)


def signature_payload(
    payload_kind: str,
    generator: str,
    generator_version: str,
    guide_format: str,
    timestamp: str,
    baseline: str,
    algorithm: str,
    key_id: str,
    guidance: str,
    local_change_baseline: str | None = None,
) -> str:
    lines = [
        f"kind={payload_kind}",
        f"generator={generator}",
        f"generator_version={generator_version}",
        f"guide_format={guide_format}",
        f"generated_at={timestamp}",
        f"git_baseline={baseline}",
    ]
    if local_change_baseline is not None:
        lines.append(f"local_change_baseline={local_change_baseline}")
    lines.extend(
        [
            f"signature_algorithm={algorithm}",
            f"signature_key_id={key_id}",
            f"guidance={guidance.strip()}",
        ]
    )
    return "\n".join(lines)


def compute_signature(
    secret: bytes,
    payload_kind: str,
    generator: str,
    generator_version: str,
    guide_format: str,
    timestamp: str,
    baseline: str,
    algorithm: str,
    key_id: str,
    guidance: str,
    local_change_baseline: str | None = None,
) -> str:
    payload = signature_payload(
        payload_kind,
        generator,
        generator_version,
        guide_format,
        timestamp,
        baseline,
        algorithm,
        key_id,
        guidance,
        local_change_baseline,
    )
    digest = hmac.new(secret, payload.encode("utf-8"), hashlib.sha256).hexdigest()
    return f"hmac-sha256:{digest}"


def guidance_body_from_block(block: str) -> str | None:
    lines = block.splitlines()
    signature_index = next((index for index, line in enumerate(lines) if line.startswith("Signature:")), None)
    if signature_index is None:
        return None

    body_start = signature_index + 1
    if body_start < len(lines) and not lines[body_start].strip():
        body_start += 1

    body_end = len(lines)
    if lines and lines[-1].strip() == END_MARKER:
        body_end -= 1

    guidance = "\n".join(lines[body_start:body_end]).strip()
    return guidance or None


def signature_is_valid(
    block: str | None,
    generator: str | None,
    generator_version: str | None,
    guide_format: str | None,
    timestamp: str | None,
    baseline: str | None,
    local_change_baseline: str | None,
    algorithm: str | None,
    key_id: str | None,
    signature: str | None,
    secret: bytes | None,
) -> bool:
    if (
        not block
        or not generator
        or not generator_version
        or not guide_format
        or not timestamp
        or baseline is None
        or not key_id
        or not signature
        or secret is None
    ):
        return False
    effective_algorithm = algorithm or (SIGNATURE_ALGORITHM if signature.startswith("hmac-sha256:") else None)
    if guide_format != GUIDE_FORMAT or effective_algorithm != SIGNATURE_ALGORITHM or not signature.startswith("hmac-sha256:"):
        return False
    guidance = guidance_body_from_block(block)
    if guidance is None:
        return False
    expected = compute_signature(
        secret,
        "project-index",
        generator,
        generator_version,
        guide_format,
        timestamp,
        baseline,
        effective_algorithm,
        key_id,
        guidance,
        local_change_baseline,
    )
    return hmac.compare_digest(signature, expected)


def top_level_section_body(guidance: str, title: str) -> str | None:
    matches = list(SECTION_HEADING_RE.finditer(guidance))
    for index, match in enumerate(matches):
        if match.group("title").strip() != title:
            continue
        end = matches[index + 1].start() if index + 1 < len(matches) else len(guidance)
        return guidance[match.end() : end].strip()
    return None


def module_entries(module_map_body: str) -> list[tuple[str, str]]:
    matches = list(MODULE_HEADING_RE.finditer(module_map_body))
    entries: list[tuple[str, str]] = []
    for index, match in enumerate(matches):
        title = match.group("title").strip()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(module_map_body)
        entries.append((title, module_map_body[match.end() : end].strip()))
    return entries


def section_span(guidance: str, title: str) -> tuple[int, int, re.Match[str]] | None:
    matches = list(SECTION_HEADING_RE.finditer(guidance))
    for index, match in enumerate(matches):
        if match.group("title").strip() != title:
            continue
        end = matches[index + 1].start() if index + 1 < len(matches) else len(guidance)
        return match.end(), end, match
    return None


def strip_inline_code(value: str) -> str:
    value = value.strip()
    if value.startswith("`") and value.endswith("`") and len(value) >= 2:
        value = value[1:-1]
    return value.strip()


def field_value(body: str, field: str) -> str | None:
    match = re.search(rf"^- {re.escape(field)}:\s*(?P<value>.*?)\s*$", body, re.MULTILINE)
    if not match:
        return None
    return match.group("value").strip()


def resolve_repo_relative_path(root: Path, raw: str, field: str) -> Path:
    cleaned = strip_inline_code(raw)
    if not cleaned:
        raise GuidanceMapError(f"{field} must not be empty.")
    path = Path(cleaned)
    resolved = path.resolve() if path.is_absolute() else (root / path).resolve()
    root_resolved = root.resolve()
    if resolved != root_resolved and root_resolved not in resolved.parents:
        raise GuidanceMapError(f"{field} path is outside repository: {cleaned}")
    return resolved


def repo_relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def module_index_descriptors(root: Path, guidance: str) -> list[dict[str, str]]:
    module_index = top_level_section_body(guidance, "Module Index") or ""
    modules = module_entries(module_index)
    if not modules:
        raise GuidanceMapError("Module Index must contain at least one '#### <module name>' entry.")

    descriptors: list[dict[str, str]] = []
    seen_guides: set[str] = set()
    for module_name, module_body in modules:
        if not module_name:
            raise GuidanceMapError("Module Index contains an empty module heading.")
        for field in REQUIRED_INDEX_MODULE_FIELDS:
            if field == "Module Signature":
                continue
            if field_value(module_body, field) is None:
                raise GuidanceMapError(f"Module '{module_name}' is missing required field: {field}.")
        guide_value = field_value(module_body, "Module Guide")
        assert guide_value is not None
        guide_path = resolve_repo_relative_path(root, guide_value, f"Module '{module_name}' Module Guide")
        guide_rel = repo_relative(root, guide_path)
        if guide_rel in seen_guides:
            raise GuidanceMapError(f"Module Guide is reused by more than one module: {guide_rel}")
        seen_guides.add(guide_rel)
        descriptors.append(
            {
                "name": module_name,
                "module_path": field_value(module_body, "Module Path") or "",
                "module_guide": guide_rel,
                "owns": field_value(module_body, "Owns") or "",
                "change_here_when": field_value(module_body, "Change here when") or "",
                "do_not_put_here": field_value(module_body, "Do not put here") or "",
                "read_guide_when": field_value(module_body, "Read guide when") or "",
                "usually_skip_when": field_value(module_body, "Usually skip when") or "",
                "signature": strip_inline_code(field_value(module_body, "Module Signature") or ""),
            }
        )
    return descriptors


def module_path_values(raw: str) -> list[str]:
    inline_values = re.findall(r"`([^`]+)`", raw)
    candidates = inline_values if inline_values else re.split(r"[,;]", raw)
    normalized: list[str] = []
    for candidate in candidates:
        value = candidate.strip().strip("`").strip()
        if not value:
            continue
        value = value.replace("\\", "/")
        if value.startswith("./"):
            value = value[2:]
        value = value.rstrip("/") or "."
        normalized.append(value)
    return unique_ordered(normalized)


def path_is_inside_module(changed_file: str, module_path: str) -> bool:
    file_path = changed_file.strip().replace("\\", "/")
    module = module_path.strip().replace("\\", "/").rstrip("/") or "."
    if module == ".":
        return True
    return file_path == module or file_path.startswith(f"{module}/")


def change_categories_for_file(file: str, impact: dict[str, list[str]]) -> list[str]:
    return [category for category, files in impact.items() if file in files]


def changed_files_by_module(
    modules: list[dict[str, object]],
    changed: list[str],
    impact: dict[str, list[str]],
) -> tuple[list[dict[str, object]], list[str]]:
    docs_only = set(impact.get("docs_only", []))
    considered = [file for file in changed if file not in docs_only]
    mapped: set[str] = set()
    affected: list[dict[str, object]] = []

    for module in modules:
        module_paths = module_path_values(str(module.get("module_path") or ""))
        if not module_paths:
            continue
        files = [
            file
            for file in considered
            if any(path_is_inside_module(file, module_path) for module_path in module_paths)
        ]
        if not files:
            continue
        mapped.update(files)
        categories = unique_ordered(
            category
            for file in files
            for category in change_categories_for_file(file, impact)
        )
        affected.append(
            {
                "name": module.get("name"),
                "module_path": module.get("module_path"),
                "module_guide": module.get("module_guide"),
                "read_guide_when": module.get("read_guide_when", ""),
                "usually_skip_when": module.get("usually_skip_when", ""),
                "changed_files": files,
                "impact_categories": categories,
            }
        )

    unmapped = [file for file in considered if file not in mapped]
    return affected, unmapped


def module_signature_block_span(text: str) -> tuple[int, int, str] | None:
    start_count = text.count(MODULE_START_MARKER)
    end_count = text.count(MODULE_END_MARKER)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1:
        raise GuidanceMapError("Malformed module signature markers: expected exactly one start and one end marker.")
    start = text.index(MODULE_START_MARKER)
    end_marker_start = text.index(MODULE_END_MARKER)
    if end_marker_start < start:
        raise GuidanceMapError("Malformed module signature markers: end marker appears before start marker.")
    end = end_marker_start + len(MODULE_END_MARKER)
    return start, end, text[start:end]


def module_body_from_text(text: str) -> str:
    found = module_signature_block_span(text)
    if found is None:
        return text.strip()
    start, end, _ = found
    return f"{text[:start].rstrip()}\n\n{text[end:].lstrip()}".strip()


def validate_module_guide_shape(module_name: str, body: str) -> None:
    stripped = body.strip()
    if not stripped:
        raise GuidanceMapError(f"Module guide '{module_name}' is empty.")
    for field in REQUIRED_MODULE_GUIDE_FIELDS:
        if not re.search(rf"^- {re.escape(field)}:\s*", stripped, re.MULTILINE):
            raise GuidanceMapError(f"Module guide '{module_name}' is missing required field: {field}.")


def compute_module_signature(
    secret: bytes,
    module_name: str,
    module_path: str,
    module_guide: str,
    timestamp: str,
    baseline: str,
    key_id: str,
    body: str,
    generator_version: str = GENERATOR_VERSION,
) -> str:
    guidance = "\n".join(
        [
            f"module_name={module_name}",
            f"module_path={module_path}",
            f"module_guide={module_guide}",
            f"module_body={body.strip()}",
        ]
    )
    return compute_signature(
        secret,
        "module-guide",
        GENERATOR,
        generator_version,
        GUIDE_FORMAT,
        timestamp,
        baseline,
        SIGNATURE_ALGORITHM,
        key_id,
        guidance,
    )


def render_module_signature_block(signature: str) -> str:
    return "\n".join([MODULE_START_MARKER, f"Signature: {signature}", MODULE_END_MARKER, ""])


def update_module_signature_text(existing: str, signature: str) -> str:
    block = render_module_signature_block(signature)
    found = module_signature_block_span(existing)
    if found is None:
        body = existing.strip()
        return f"{block}\n{body}\n" if body else block
    start, end, _ = found
    before = existing[:start].rstrip()
    after = existing[end:].lstrip()
    pieces = []
    if before:
        pieces.append(before)
    pieces.append(block.rstrip())
    if after:
        pieces.append(after.rstrip())
    return "\n\n".join(pieces) + "\n"


def sign_module_guides(
    root: Path,
    guidance: str,
    timestamp: str,
    baseline: str,
    key_id: str,
    secret: bytes,
) -> list[dict[str, str]]:
    descriptors = module_index_descriptors(root, guidance)
    signed: list[dict[str, str]] = []
    for descriptor in descriptors:
        guide_path = (root / descriptor["module_guide"]).resolve()
        if not guide_path.exists():
            raise GuidanceMapError(f"Module guide does not exist for '{descriptor['name']}': {descriptor['module_guide']}")
        body = module_body_from_text(read_text(guide_path))
        validate_module_guide_shape(descriptor["name"], body)
        signature = compute_module_signature(
            secret,
            descriptor["name"],
            descriptor["module_path"],
            descriptor["module_guide"],
            timestamp,
            baseline,
            key_id,
            body,
        )
        write_text(guide_path, update_module_signature_text(read_text(guide_path), signature))
        signed.append({**descriptor, "signature": signature})
    return signed


def module_signature_from_text(text: str) -> str | None:
    found = module_signature_block_span(text)
    if found is None:
        return None
    return metadata_value(SIGNATURE_RE, found[2])


def module_signature_is_valid(
    root: Path,
    descriptor: dict[str, str],
    generator_version: str | None,
    timestamp: str | None,
    baseline: str | None,
    key_id: str | None,
    secret: bytes | None,
) -> tuple[bool, str | None]:
    if not generator_version or not timestamp or baseline is None or not key_id or secret is None:
        return False, None
    guide_path = (root / descriptor["module_guide"]).resolve()
    if not guide_path.exists():
        return False, None
    text = read_text(guide_path)
    signature = module_signature_from_text(text)
    if not signature or not signature.startswith("hmac-sha256:"):
        return False, signature
    body = module_body_from_text(text)
    expected = compute_module_signature(
        secret,
        descriptor["name"],
        descriptor["module_path"],
        descriptor["module_guide"],
        timestamp,
        baseline,
        key_id,
        body,
        generator_version,
    )
    return hmac.compare_digest(signature, expected), signature


def module_statuses(
    root: Path,
    guidance: str | None,
    generator_version: str | None,
    timestamp: str | None,
    baseline: str | None,
    key_id: str | None,
    secret: bytes | None,
) -> list[dict[str, object]]:
    if not guidance:
        return []
    try:
        descriptors = module_index_descriptors(root, guidance)
    except GuidanceMapError:
        return []

    statuses: list[dict[str, object]] = []
    for descriptor in descriptors:
        guide_path = (root / descriptor["module_guide"]).resolve()
        signature_valid, file_signature = module_signature_is_valid(root, descriptor, generator_version, timestamp, baseline, key_id, secret)
        index_signature = descriptor.get("signature") or None
        statuses.append(
            {
                "name": descriptor["name"],
                "module_path": descriptor["module_path"],
                "module_guide": descriptor["module_guide"],
                "module_guide_exists": guide_path.exists(),
                "index_module_signature": index_signature,
                "module_signature": file_signature,
                "module_signature_matches_index": bool(index_signature and file_signature and index_signature == file_signature),
                "module_signature_valid": signature_valid,
                "read_guide_when": descriptor.get("read_guide_when", ""),
                "usually_skip_when": descriptor.get("usually_skip_when", ""),
            }
        )
    return statuses


def update_signature_field(module_body: str, signature: str) -> str:
    replacement = f"- Module Signature: `{signature}`"
    if field_value(module_body, "Module Signature") is not None:
        return re.sub(r"^- Module Signature:\s*.*$", replacement, module_body, count=1, flags=re.MULTILINE)

    lines = module_body.splitlines()
    for index, line in enumerate(lines):
        if line.startswith("- Module Guide:"):
            lines.insert(index + 1, replacement)
            return "\n".join(lines).strip()
    lines.insert(0, replacement)
    return "\n".join(lines).strip()


def update_module_index_signatures(guidance: str, signed_modules: list[dict[str, str]]) -> str:
    span = section_span(guidance, "Module Index")
    if span is None:
        raise GuidanceMapError("Guidance content is missing required section: Module Index.")
    body_start, body_end, _ = span
    module_index_body = guidance[body_start:body_end].strip()
    matches = list(MODULE_HEADING_RE.finditer(module_index_body))
    signatures = {module["name"]: module["signature"] for module in signed_modules}
    pieces: list[str] = []
    cursor = 0
    for index, match in enumerate(matches):
        module_name = match.group("title").strip()
        entry_body_start = match.end()
        entry_end = matches[index + 1].start() if index + 1 < len(matches) else len(module_index_body)
        pieces.append(module_index_body[cursor:entry_body_start])
        entry_body = module_index_body[entry_body_start:entry_end].strip()
        if module_name in signatures:
            pieces.append("\n\n" + update_signature_field(entry_body, signatures[module_name]) + "\n")
        else:
            pieces.append(module_index_body[entry_body_start:entry_end])
        cursor = entry_end
    pieces.append(module_index_body[cursor:])
    updated_body = "".join(pieces).strip()
    return f"{guidance[:body_start].rstrip()}\n\n{updated_body}\n{guidance[body_end:].lstrip()}".strip()


def validate_guidance_shape(guidance: str) -> None:
    stripped = guidance.strip()
    if not stripped:
        raise GuidanceMapError("Guidance content is empty.")
    section_positions: list[int] = []
    for section in REQUIRED_GUIDE_SECTIONS:
        match = re.search(rf"^### {re.escape(section)}\s*$", stripped, re.MULTILINE)
        if match is None:
            raise GuidanceMapError(f"Guidance content is missing required section: {section}.")
        section_positions.append(match.start())
    if section_positions != sorted(section_positions):
        raise GuidanceMapError(
            "Guidance sections must be ordered as: "
            + ", ".join(REQUIRED_GUIDE_SECTIONS)
            + "."
        )

    editing_rules = top_level_section_body(stripped, "Agent Editing Rules") or ""
    if not re.search(r"^- \[(MUST|SHOULD|AVOID)\]\s+\S", editing_rules, re.MULTILINE):
        raise GuidanceMapError("Agent Editing Rules must contain tagged bullets such as [MUST], [SHOULD], or [AVOID].")

    task_routing = top_level_section_body(stripped, "Task Routing") or ""
    if not re.search(r"^- To .+?:\s+\S", task_routing, re.MULTILINE):
        raise GuidanceMapError("Task Routing must contain bullets shaped like '- To <task>: ...'.")

    dependency_rules = top_level_section_body(stripped, "Module Dependency Rules") or ""
    if not re.search(r"^- \S", dependency_rules, re.MULTILINE):
        raise GuidanceMapError("Module Dependency Rules must contain at least one bullet.")

    module_index = top_level_section_body(stripped, "Module Index") or ""
    modules = module_entries(module_index)
    if not modules:
        raise GuidanceMapError("Module Index must contain at least one '#### <module name>' entry.")
    for module_name, module_body in modules:
        if not module_name:
            raise GuidanceMapError("Module Index contains an empty module heading.")
        for field in REQUIRED_INDEX_MODULE_FIELDS:
            if field == "Module Signature":
                continue
            if not re.search(rf"^- {re.escape(field)}:\s*", module_body, re.MULTILINE):
                raise GuidanceMapError(f"Module '{module_name}' is missing required field: {field}.")


def render_block(
    guidance: str,
    timestamp: str,
    baseline: str,
    key_id: str,
    secret: bytes,
    generator_version: str = GENERATOR_VERSION,
    local_change_baseline_value: str | None = None,
) -> str:
    if START_MARKER in guidance or END_MARKER in guidance:
        raise GuidanceMapError("Guidance content must not contain guidance block markers.")
    guidance = guidance.strip()
    if not guidance:
        raise GuidanceMapError("Guidance content is empty.")
    signature = compute_signature(
        secret,
        "project-index",
        GENERATOR,
        generator_version,
        GUIDE_FORMAT,
        timestamp,
        baseline,
        SIGNATURE_ALGORITHM,
        key_id,
        guidance,
        local_change_baseline_value,
    )
    local_baseline_lines = []
    if local_change_baseline_value is not None:
        local_baseline_lines.append(f"Local change baseline: {local_change_baseline_value}")
    return "\n".join(
        [
            START_MARKER,
            "## Code Project Guidance Map",
            "",
            f"Generator: {GENERATOR}",
            f"Generator version: {generator_version}",
            f"Guide format: {GUIDE_FORMAT}",
            f"Generated at: {timestamp}",
            f"Git baseline: {baseline}",
            *local_baseline_lines,
            f"Signature key id: {key_id}",
            f"Signature: {signature}",
            "",
            guidance,
            END_MARKER,
            "",
        ]
    )


def update_agents_text(existing: str, block: str) -> str:
    found = find_block(existing)
    if found is None:
        prefix = existing.rstrip()
        if prefix:
            return f"{prefix}\n\n{block}"
        return block
    start, end, _ = found
    before = existing[:start].rstrip()
    after = existing[end:].lstrip()
    pieces = []
    if before:
        pieces.append(before)
    pieces.append(block.rstrip())
    if after:
        pieces.append(after.rstrip())
    return "\n\n".join(pieces) + "\n"


def status(repo_arg: Path) -> dict[str, object]:
    root, git_available = repo_root(repo_arg)
    agents_path = root / "AGENTS.md"
    exists = agents_path.exists()
    text = read_text(agents_path) if exists else ""
    block_info = find_block(text) if exists else None
    block = block_info[2] if block_info else None
    generated_at = metadata_value(GENERATED_AT_RE, block)
    generator = metadata_value(GENERATOR_RE, block)
    generator_version = metadata_value(GENERATOR_VERSION_RE, block)
    legacy_generated_by = metadata_value(LEGACY_GENERATED_BY_RE, block)
    guide_format = metadata_value(GUIDE_FORMAT_RE, block)
    git_baseline = metadata_value(GIT_BASELINE_RE, block)
    local_change_baseline_value = metadata_value(LOCAL_CHANGE_BASELINE_RE, block)
    local_change_baseline_entries, local_change_baseline_valid = decode_local_change_baseline(local_change_baseline_value)
    signature_key_id = metadata_value(SIGNATURE_KEY_ID_RE, block)
    signature_algorithm = metadata_value(SIGNATURE_ALGORITHM_RE, block)
    signature = metadata_value(SIGNATURE_RE, block)
    parsed_generated_at = parse_iso_datetime(generated_at)
    has_block = block is not None
    generated_at_valid = (not has_block and generated_at is None) or parsed_generated_at is not None
    version_status = generator_version_status(generator_version) if has_block else None
    generator_version_valid = (not has_block and generator_version is None) or version_status in {
        "current",
        "patch-compatible",
    }
    generator_version_requires_full_read = has_block and version_status in {"missing", "invalid", "incompatible"}
    guide_format_valid = (not has_block and guide_format is None) or guide_format == GUIDE_FORMAT
    signature_secret, signature_key_available, signature_key_source = load_signature_secret(signature_key_id, create=False)
    signature_valid = (
        signature_is_valid(
            block,
            generator,
            generator_version,
            guide_format,
            generated_at,
            git_baseline,
            local_change_baseline_value,
            signature_algorithm,
            signature_key_id,
            signature,
            signature_secret,
        )
        if has_block
        else None
    )
    guidance_body = guidance_body_from_block(block) if block else None
    module_results = module_statuses(
        root,
        guidance_body,
        generator_version,
        generated_at,
        git_baseline,
        signature_key_id,
        signature_secret,
    )
    modules_valid = bool(module_results) and all(
        bool(module["module_guide_exists"])
        and bool(module["module_signature_valid"])
        and bool(module["module_signature_matches_index"])
        for module in module_results
    )
    requires_full_read = (not has_block) or (
        has_block
        and (
            not generator_version_valid
            or generator_version_requires_full_read
            or not guide_format_valid
            or not generated_at_valid
            or not local_change_baseline_valid
            or not signature_valid
        )
    )
    changes = changed_files(root, git_available, parsed_generated_at, local_change_baseline_entries)

    return {
        "repo_root": str(root),
        "project_id": project_id(root, git_available),
        "agents_path": str(agents_path),
        "agents_exists": exists,
        "has_block": has_block,
        "generator": generator,
        "generator_version": generator_version,
        "current_generator_version": GENERATOR_VERSION,
        "generator_version_status": version_status,
        "generator_version_valid": generator_version_valid,
        "generated_by": legacy_generated_by,
        "guide_format": guide_format,
        "guide_format_valid": guide_format_valid,
        "generated_at": generated_at,
        "generated_at_valid": generated_at_valid,
        "git_baseline": git_baseline,
        "local_change_baseline": local_change_baseline_value,
        "local_change_baseline_valid": local_change_baseline_valid,
        "signature_key_id": signature_key_id,
        "signature_key_available": signature_key_available if has_block else None,
        "signature_key_source": signature_key_source if has_block else None,
        "signature_algorithm": signature_algorithm,
        "signature": signature,
        "signature_valid": signature_valid,
        "modules": module_results,
        "modules_valid": modules_valid if has_block else None,
        "requires_module_refresh": bool(has_block and not requires_full_read and not modules_valid),
        "git_available": git_available,
        "current_head": current_head(root, git_available),
        "changed_files": changes["all"],
        "changed_files_by_source": changes,
        "requires_full_read": requires_full_read,
    }


def verify(repo_arg: Path) -> dict[str, object]:
    current = status(repo_arg)
    changed = current["changed_files"]
    impact = classify_changed_files(changed if isinstance(changed, list) else [])
    modules = current["modules"] if isinstance(current.get("modules"), list) else []
    affected_modules, unmapped_changed_files = changed_files_by_module(
        modules if isinstance(modules, list) else [],
        changed if isinstance(changed, list) else [],
        impact,
    )
    affected_module_guides = unique_ordered(
        str(module.get("module_guide") or "")
        for module in affected_modules
        if module.get("module_guide")
    )
    reasons: list[str] = []
    recommended_action = "none"
    severity = "ok"

    if current["requires_full_read"]:
        recommended_action = "full_refresh"
        severity = "error"
        if not current["has_block"]:
            reasons.append("AGENTS.md guidance block is missing.")
        if current["has_block"] and not current["generator_version_valid"]:
            reasons.append(
                "Generator version is missing, invalid, or incompatible; perform a full refresh with the current plugin."
            )
        if current["has_block"] and not current["generated_at_valid"]:
            reasons.append("Generated at timestamp is missing or invalid.")
        if current["has_block"] and not current["guide_format_valid"]:
            reasons.append("Guide format is missing or unsupported.")
        if current["has_block"] and not current["local_change_baseline_valid"]:
            reasons.append("Local change baseline is malformed; refresh the guidance map with the current plugin.")
        if current["has_block"] and not current["signature_key_available"]:
            reasons.append("Signature key is unavailable; this block must be refreshed by the plugin or verified with the configured key.")
        if current["has_block"] and not current["signature_valid"]:
            reasons.append("Signature metadata is missing or invalid.")
    elif current.get("requires_module_refresh"):
        recommended_action = "refresh_affected_modules"
        severity = "warning"
        reasons.append("One or more module guide files are missing, unsigned, or no longer match their module signature.")
    else:
        if current["generator_version_status"] == "patch-compatible":
            severity = "info"
            reasons.append(
                "Generator patch version differs but is semver-compatible; existing guidance can be reused."
            )
        if impact["boundary_rules"]:
            recommended_action = "refresh_dependency_rules"
            severity = "warning"
            reasons.append("Boundary-sensitive files changed; re-evaluate Agent Editing Rules and Module Dependency Rules.")
        elif impact["task_routing"]:
            recommended_action = "refresh_task_routing_and_affected_modules"
            severity = "warning"
            reasons.append("Task-routing files changed; refresh routing guidance and affected modules.")
        elif impact["module_internal"]:
            recommended_action = "refresh_affected_modules"
            severity = "warning"
            reasons.append("Module-internal code changed; refresh affected module entries.")
        elif impact["other"]:
            recommended_action = "review_changed_files"
            severity = "info"
            reasons.append("Unclassified files changed; review whether guidance should be refreshed.")
        elif impact["docs_only"]:
            severity = "info"
            reasons.append("Only documentation or CI files changed; guidance refresh is not required.")

    if current["has_block"] and unmapped_changed_files:
        code_unmapped = [
            file
            for file in unmapped_changed_files
            if file in impact["boundary_rules"] or file in impact["task_routing"] or file in impact["module_internal"]
        ]
        if code_unmapped:
            preview = ", ".join(code_unmapped[:5])
            suffix = " ..." if len(code_unmapped) > 5 else ""
            reasons.append(f"Some changed files do not map to any Module Index entry; review module boundaries: {preview}{suffix}")

    return {
        **current,
        "change_impact": impact,
        "affected_modules": affected_modules,
        "affected_module_guides": affected_module_guides,
        "unmapped_changed_files": unmapped_changed_files,
        "stale": recommended_action not in {"none", "review_changed_files"},
        "severity": severity,
        "recommended_action": recommended_action,
        "reasons": reasons,
    }


def update(repo_arg: Path, guidance_file: Path, timestamp: str | None) -> dict[str, object]:
    root, git_available = repo_root(repo_arg)
    agents_path = root / "AGENTS.md"
    guidance = read_text(guidance_file)
    validate_guidance_shape(guidance)
    timestamp = timestamp or datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    baseline = current_head(root, git_available)
    existing = read_text(agents_path) if agents_path.exists() else ""
    existing_block_info = find_block(existing) if existing else None
    existing_block = existing_block_info[2] if existing_block_info else None
    key_id = metadata_value(SIGNATURE_KEY_ID_RE, existing_block) or default_signature_key_id(root, git_available)
    signature_secret, signature_key_available, signature_key_source = load_signature_secret(key_id, create=True)
    if not signature_key_available or signature_secret is None:
        raise GuidanceMapError("Unable to create or load the signature key.")
    local_baseline = local_change_baseline(root, git_available)
    signed_modules = sign_module_guides(root, guidance, timestamp, baseline, key_id, signature_secret)
    guidance = update_module_index_signatures(guidance, signed_modules)
    validate_guidance_shape(guidance)
    block = render_block(guidance, timestamp, baseline, key_id, signature_secret, local_change_baseline_value=local_baseline)
    updated = update_agents_text(existing, block)
    write_text(agents_path, updated)
    return {
        "repo_root": str(root),
        "agents_path": str(agents_path),
        "has_block": True,
        "generated_at": timestamp,
        "git_baseline": baseline,
        "local_change_baseline": local_baseline,
        "signature_key_id": key_id,
        "signature_key_source": signature_key_source,
        "modules": signed_modules,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Manage the AGENTS.md guidance map block.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    status_parser = subparsers.add_parser("status", help="Inspect AGENTS.md and Git delta state.")
    status_parser.add_argument("--repo", default=".", help="Repository or project directory.")

    verify_parser = subparsers.add_parser("verify", help="Classify guidance freshness for CI or local checks.")
    verify_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    verify_parser.add_argument(
        "--fail-on",
        choices=("never", "stale", "error"),
        default="never",
        help="Exit with code 1 when the selected condition is met.",
    )

    update_parser = subparsers.add_parser("update", help="Create or replace the signed AGENTS.md project index.")
    update_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    update_parser.add_argument("--guidance-file", required=True, help="Markdown file containing the project index draft.")
    update_parser.add_argument("--timestamp", help="ISO-8601 timestamp override for tests.")

    build_parser = subparsers.add_parser("build", help="Start or coordinate the single guidance-map builder agent.")
    build_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    build_parser.add_argument("--reason", help="Short reason for this build request.")
    build_parser.add_argument("--context", help="Context to synchronize into the builder request.")
    build_parser.add_argument("--context-file", type=Path, help="File containing context to synchronize into the builder request.")
    build_parser.add_argument("--codex-command", help="Command used to launch Codex; defaults to `codex`.")
    build_parser.add_argument(
        "--launcher",
        choices=("auto", "cli", "desktop"),
        default=None,
        help="Builder launcher. auto uses CLI when available and Desktop handoff from Codex Desktop otherwise.",
    )
    build_parser.add_argument("--model", help="Optional model passed through to `codex exec`.")
    build_parser.add_argument(
        "--agent-arg",
        action="append",
        default=[],
        help="Additional argument passed through to `codex exec`; repeat for multiple arguments.",
    )

    attach_parser = subparsers.add_parser("build-attach", help="Attach a Codex Desktop-created builder thread to a build lease.")
    attach_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    attach_parser.add_argument("--build-id", required=True, help="Active build id.")
    attach_parser.add_argument("--thread-id", required=True, help="Created Codex Desktop thread id.")

    drain_parser = subparsers.add_parser("build-drain", help="Drain pending build contexts for the active builder.")
    drain_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    drain_parser.add_argument("--build-id", required=True, help="Active build id.")

    finish_parser = subparsers.add_parser("build-finish", help="Release the active guidance-map builder lease.")
    finish_parser.add_argument("--repo", default=".", help="Repository or project directory.")
    finish_parser.add_argument("--build-id", required=True, help="Active build id.")
    finish_parser.add_argument("--status", choices=("complete", "failed", "abandoned"), required=True)
    finish_parser.add_argument("--message", help="Optional finish message.")
    finish_parser.add_argument("--force", action="store_true", help="Release even when pending contexts exist.")

    args = parser.parse_args()
    try:
        if args.command == "status":
            output = status(Path(args.repo))
        elif args.command == "verify":
            output = verify(Path(args.repo))
        elif args.command == "update":
            output = update(Path(args.repo), Path(args.guidance_file), args.timestamp)
        elif args.command == "build":
            output = start_guidance_build(
                Path(args.repo),
                reason=args.reason,
                context=args.context,
                context_file=args.context_file,
                codex_command=args.codex_command,
                model=args.model,
                extra_args=args.agent_arg,
                launcher=args.launcher,
            )
        elif args.command == "build-attach":
            output = attach_desktop_builder_thread(Path(args.repo), args.build_id, args.thread_id)
        elif args.command == "build-drain":
            output = drain_build_context(Path(args.repo), args.build_id)
        else:
            output = finish_guidance_build(
                Path(args.repo),
                args.build_id,
                args.status,
                message=args.message,
                force=args.force,
            )
    except GuidanceMapError as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 2

    print(json.dumps(output, ensure_ascii=False, indent=2))
    if args.command == "verify":
        if args.fail_on == "error" and output["severity"] == "error":
            return 1
        if args.fail_on == "stale" and (output["stale"] or output["severity"] == "error"):
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
